language: python
python:
  - "2.7"
before_install:
  - "wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
addons:
  sauce_connect:
    username: "soulnai"
    access_key: "e6f43059-2593-4fea-9ce1-757a1ead09d2"
# command to run tests
script: nosetests